[package]
name = "base"
version = "0.16.0"
description = "The Motoko base library"
repository = "https://github.com/dfinity/motoko-base"
keywords = [ "base" ]
license = "Apache-2.0"

[dev-dependencies]
matchers = "https://github.com/kritzcreek/motoko-matchers#2.1.0@781eb4980bf423816438bdaaeaa00dbdb45169ae"
core = "https://github.com/dfinity/motoko-core"

[toolchain]
moc = "0.16.0"
wasmtime = "35.0.0"
