[package]
name = "base"
version = "0.14.11"
description = "The Motoko base library"
repository = "https://github.com/dfinity/motoko-base"
keywords = [ "base" ]
license = "Apache-2.0"

[dev-dependencies]
matchers = "https://github.com/kritzcreek/motoko-matchers#v1.3.0@3dac8a071b69e4e651b25a7d9683fe831eb7cffd"

[toolchain]
moc = "0.14.11"
wasmtime = "21.0.0"
