name: Sync master and next-moc
on:
  push:
    branches:
      - sync-next-moc
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Merge master -> next-moc
        uses: robotology/gh-action-nightly-merge@v1.2.0
        with:
          stable_branch: 'master'
          development_branch: 'next-moc'
          allow_ff: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
